import viralImg from '../public/viral-gf2.jpg'

export const movies = [
  {
    id: 1,
    title: "Neon Shadows",
    genre: "Thriller",
    rating: "18+",
    year: 2024,
    duration: "2h 15m",
    score: 8.4,
    description: "A detective dives into the city's darkest underground to uncover a conspiracy that goes all the way to the top.",
    longDescription: "When veteran detective Marcus Cole receives an anonymous tip about a string of disappearances in the city's neon-lit underbelly, he quickly realizes the case goes far deeper than anyone imagined. As he peels back layers of corruption, he finds himself entangled in a web of power, betrayal, and moral compromise that threatens not just his career — but his life.",
    image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=400&h=600&fit=crop",
    backdrop: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=1200&h=600&fit=crop",
    tags: ["Crime", "Neo-noir", "Mystery"],
    featured: true,
    director: "David Fincher",
    studio: "Dark Horse Films",
    language: "English",
    country: "USA",
    cast: ["James McAvoy", "Lupita Nyong'o", "Oscar Isaac", "Cate Blanchett"],
    reviews: [
      { user: "CinemaVault", rating: 9, comment: "A masterclass in neo-noir tension. Every frame drips with atmosphere." },
      { user: "DarkScreens", rating: 8, comment: "Gripping from start to finish. The twist in act three is unforgettable." },
      { user: "NightOwlCritic", rating: 8, comment: "McAvoy delivers one of his best performances to date." },
    ],
    scoreBreakdown: { story: 88, visuals: 92, acting: 90, pacing: 84 },
  },
  {
    id: 2,
    title: "Crimson Tide",
    genre: "Action",
    rating: "18+",
    year: 2023,
    duration: "1h 58m",
    score: 7.9,
    description: "An elite soldier goes rogue after discovering his unit was used as pawns in a global arms deal.",
    longDescription: "Sergeant Dax Mercer was the best operative his country had. But when a classified mission goes sideways and his entire unit is left for dead, he uncovers a conspiracy that reaches the highest levels of government. Armed with nothing but his training and a burning need for justice, Dax wages a one-man war against the people who betrayed him.",
    image: "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=400&h=600&fit=crop",
    backdrop: "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=1200&h=600&fit=crop",
    tags: ["Action", "Military", "Conspiracy"],
    featured: false,
    director: "Antoine Fuqua",
    studio: "Apex Pictures",
    language: "English",
    country: "USA",
    cast: ["Idris Elba", "Ana de Armas", "Michael Shannon", "Zoe Saldana"],
    reviews: [
      { user: "ActionJunkie99", rating: 8, comment: "Non-stop adrenaline. The action choreography is top tier." },
      { user: "FilmBuff_X", rating: 7, comment: "Solid thriller with a few predictable beats but great performances." },
      { user: "CriticalEye", rating: 8, comment: "Elba is magnetic. Carries every scene effortlessly." },
    ],
    scoreBreakdown: { story: 76, visuals: 88, acting: 82, pacing: 90 },
  },
  {
    id: 3,
    title: "Void Protocol",
    genre: "Sci-Fi",
    rating: "18+",
    year: 2024,
    duration: "2h 32m",
    score: 9.1,
    description: "In 2087, a scientist discovers that reality itself is a simulation — and someone is pulling the plug.",
    longDescription: "Dr. Elara Voss has spent her career studying quantum consciousness. When her research leads her to an impossible conclusion — that the universe is a constructed simulation — she must decide whether to expose the truth or protect the billions who would be shattered by it. But the architects of the simulation have already noticed her, and they're not willing to let her talk.",
    image: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=400&h=600&fit=crop",
    backdrop: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=1200&h=600&fit=crop",
    tags: ["Sci-Fi", "Dystopia", "Mind-bending"],
    featured: true,
    director: "Denis Villeneuve",
    studio: "Quantum Studios",
    language: "English",
    country: "Canada / USA",
    cast: ["Tilda Swinton", "Mahershala Ali", "Florence Pugh", "Keanu Reeves"],
    reviews: [
      { user: "SciFiOracle", rating: 10, comment: "The most ambitious sci-fi film in a decade. Absolutely mind-blowing." },
      { user: "PhilosophyOfFilm", rating: 9, comment: "Raises questions that will haunt you for days. Villeneuve at his peak." },
      { user: "CinemaVault", rating: 9, comment: "Visually stunning and intellectually daring. A rare achievement." },
    ],
    scoreBreakdown: { story: 96, visuals: 98, acting: 92, pacing: 86 },
  },
  {
    id: 4,
    title: "Blood Meridian",
    genre: "Western",
    rating: "18+",
    year: 2023,
    duration: "2h 45m",
    score: 8.7,
    description: "A brutal journey through the lawless frontier where violence and survival are the only constants.",
    longDescription: "Set in the scorched borderlands of 1850s America, Blood Meridian follows a nameless drifter who falls in with a gang of scalp hunters led by the terrifying Judge Holden. What begins as a tale of survival quickly becomes a meditation on the nature of violence, evil, and the darkness that lives in the heart of civilization itself.",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=400&h=600&fit=crop",
    backdrop: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=1200&h=600&fit=crop",
    tags: ["Western", "Brutal", "Epic"],
    featured: false,
    director: "John Hillcoat",
    studio: "Frontier Films",
    language: "English",
    country: "USA",
    cast: ["Mads Mikkelsen", "Tom Hardy", "Thomasin McKenzie", "Javier Bardem"],
    reviews: [
      { user: "WesternFanatic", rating: 9, comment: "Brutal, beautiful, and unforgettable. A true epic." },
      { user: "DarkScreens", rating: 8, comment: "Not for the faint of heart, but an absolute masterpiece of the genre." },
      { user: "FilmBuff_X", rating: 9, comment: "Mikkelsen is terrifying. One of the best villain performances ever." },
    ],
    scoreBreakdown: { story: 90, visuals: 94, acting: 95, pacing: 78 },
  },
  {
    id: 5,
    title: "Dark Frequency",
    genre: "Horror",
    rating: "18+",
    year: 2024,
    duration: "1h 44m",
    score: 7.6,
    description: "A radio host begins receiving transmissions from the dead — and they want something back.",
    longDescription: "Late-night radio host Nora Vane has always been a skeptic. But when her midnight show starts picking up voices that don't belong to any living caller, she's forced to confront the terrifying possibility that the dead are trying to reach her — and that they have unfinished business. As the transmissions grow more desperate, so does the danger.",
    image: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=400&h=600&fit=crop",
    backdrop: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=1200&h=600&fit=crop",
    tags: ["Horror", "Supernatural", "Psychological"],
    featured: false,
    director: "Mike Flanagan",
    studio: "Midnight Pictures",
    language: "English",
    country: "USA",
    cast: ["Anya Taylor-Joy", "Ethan Hawke", "Viola Davis", "Willem Dafoe"],
    reviews: [
      { user: "HorrorHound", rating: 8, comment: "Genuinely unsettling. The sound design alone will give you nightmares." },
      { user: "NightOwlCritic", rating: 7, comment: "Slow burn that pays off in the final act. Taylor-Joy is excellent." },
      { user: "ScreamQueen", rating: 8, comment: "Flanagan does it again. Atmospheric horror at its finest." },
    ],
    scoreBreakdown: { story: 80, visuals: 82, acting: 86, pacing: 72 },
  },
  {
    id: 6,
    title: "The Last Cartel",
    genre: "Crime",
    rating: "18+",
    year: 2023,
    duration: "2h 20m",
    score: 8.2,
    description: "A DEA agent goes undercover so deep he starts to forget which side he's on.",
    longDescription: "Agent Ray Salazar has been undercover for three years. He's built a life, earned trust, and become indispensable to the cartel. But when a new operation threatens to expose him, Ray must make an impossible choice: complete his mission and destroy everything he's built, or disappear into the life he was only supposed to be pretending to live.",
    image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400&h=600&fit=crop",
    backdrop: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1200&h=600&fit=crop",
    tags: ["Crime", "Undercover", "Drama"],
    featured: false,
    director: "Ridley Scott",
    studio: "Black Sun Productions",
    language: "English / Spanish",
    country: "USA / Mexico",
    cast: ["Oscar Isaac", "Penélope Cruz", "Benicio del Toro", "Jennifer Lopez"],
    reviews: [
      { user: "CrimeDrama101", rating: 8, comment: "Tense, layered, and brilliantly acted. Isaac is phenomenal." },
      { user: "CinemaVault", rating: 8, comment: "Ridley Scott reminds us why he's a master of the genre." },
      { user: "FilmBuff_X", rating: 9, comment: "The moral ambiguity is what makes this film so compelling." },
    ],
    scoreBreakdown: { story: 88, visuals: 84, acting: 92, pacing: 80 },
  },
  {
    id: 7,
    title: "Fracture Point",
    genre: "Thriller",
    rating: "18+",
    year: 2024,
    duration: "1h 52m",
    score: 7.8,
    description: "A hostage negotiator faces her most personal case yet when her own family is taken.",
    longDescription: "FBI negotiator Claire Holt has talked down hundreds of hostage situations. But when she arrives at a scene to find her own husband and daughter being held, every protocol she's ever followed becomes meaningless. Now she must navigate the most dangerous negotiation of her life — one where the stakes are everything she loves.",
    image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=400&h=600&fit=crop",
    backdrop: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=1200&h=600&fit=crop",
    tags: ["Thriller", "Suspense", "Drama"],
    featured: false,
    director: "Kathryn Bigelow",
    studio: "Tension Films",
    language: "English",
    country: "USA",
    cast: ["Charlize Theron", "Joel Edgerton", "Rami Malek", "Halle Berry"],
    reviews: [
      { user: "ThrillerAddict", rating: 8, comment: "Edge-of-your-seat tension from the first minute to the last." },
      { user: "ActionJunkie99", rating: 7, comment: "Theron is incredible. The script could be tighter but the ride is worth it." },
      { user: "CriticalEye", rating: 8, comment: "Bigelow knows how to build dread. A taut, gripping thriller." },
    ],
    scoreBreakdown: { story: 82, visuals: 80, acting: 88, pacing: 86 },
  },
  {
    id: 8,
    title: "Tamil Movie",
    genre: "Sci-Fi",
    rating: "18+",
    year: 2023,
    duration: "2h 8m",
    score: 8.0,
    description: "The last surviving crew of a deep-space mission must decide who lives when oxygen runs out.",
    longDescription: "Six months into a deep-space mission, the crew of the Ares IV discovers their oxygen recycler is failing. With only enough air for four of the six crew members to survive the journey home, they must make an impossible decision. As alliances form and fracture, the true nature of each person is revealed in the cold silence of space.",
    image: viralImg,
    backdrop: "https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=1200&h=600&fit=crop",
    tags: ["Sci-Fi", "Space", "Survival"],
    featured: false,
    director: "Alex Garland",
    studio: "Orbit Pictures",
    language: "English",
    country: "UK / USA",
    cast: ["Cillian Murphy", "Zendaya", "Adam Driver", "Lupita Nyong'o"],
    reviews: [
      { user: "SciFiOracle", rating: 8, comment: "Claustrophobic and morally complex. Garland at his most restrained." },
      { user: "PhilosophyOfFilm", rating: 8, comment: "A haunting thought experiment wrapped in a survival thriller." },
      { user: "NightOwlCritic", rating: 8, comment: "Murphy and Driver are electric together. Unmissable." },
    ],
    scoreBreakdown: { story: 84, visuals: 86, acting: 88, pacing: 82 },
  },
];

export const genres = ["All", "Thriller", "Action", "Sci-Fi", "Western", "Horror", "Crime"];

export function getMovieById(id) {
  return movies.find((m) => m.id === parseInt(id));
}

export function getFeaturedMovies() {
  return movies.filter((m) => m.featured);
}
